
INSERT INTO BUG (ID, ASSIGNED_ID, AUTHOR_ID, DESCRIPTION, FIXEDIN, LOCKVERSION, SEVERITY, STATUS, TARGETDATE, TITLE, VERSION) VALUES (7, 1, 1, 'sdfasdfsa', '1.3', 1, 'Medium', 1, 'dsafsad', 'Buggy', '1.2.3');
INSERT INTO BUG (ID, ASSIGNED_ID, AUTHOR_ID, DESCRIPTION, FIXEDIN, LOCKVERSION, SEVERITY, STATUS, TARGETDATE, TITLE, VERSION) VALUES (9, 1, 1, 'leiras', '6.5', 1, 'High', 1, 'dsafsad', 'aBuggy', '4.3');
INSERT INTO BUG (ID, ASSIGNED_ID, AUTHOR_ID, DESCRIPTION, FIXEDIN, LOCKVERSION, SEVERITY, STATUS, TARGETDATE, TITLE, VERSION) VALUES (1, 1, 1, 'asdfasdfsa', '3.3', 1, 'dsfsdf', 1, 'dsafsad', 'nemBug', '1');
